<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color: #1f2937; margin: 48px 56px; }
        .letterhead { border-bottom: 2px solid #4f46e5; padding-bottom: 12px; margin-bottom: 28px; }
        .letterhead h1 { font-size: 16px; color: #4f46e5; margin: 0; }
        .letterhead p { margin: 2px 0 0; color: #6b7280; font-size: 9px; }
        .meta { margin-bottom: 24px; color: #6b7280; font-size: 10px; }
        .meta strong { color: #1f2937; }
        h2 { font-size: 13px; margin: 0 0 16px; }
        .body { white-space: pre-wrap; line-height: 1.55; }
        .footer { margin-top: 40px; padding-top: 10px; border-top: 1px solid #e5e7eb; color: #9ca3af; font-size: 8px; }
    </style>
</head>
<body>
    <div class="letterhead">
        <h1>IPMS Partners LLP</h1>
        <p>Intellectual Property Attorneys · 1 Inventors Square, London EC1 · ipms.example</p>
    </div>

    <div class="meta">
        Our ref: <strong>{{ $matter->reference }}</strong>
        @if ($matter->application_no) · Application: <strong>{{ $matter->application_no }}</strong> @endif
        · {{ now()->format('j F Y') }}
    </div>

    @if ($subject)
        <h2>{{ $subject }}</h2>
    @endif

    <div class="body">{{ $body }}</div>

    <div class="footer">
        Generated by IPMS for matter {{ $matter->reference }} — {{ $matter->title }}
    </div>
</body>
</html>
